<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/css/main.css">
    <title>Tradingview</title>
</head>
<body>
<div class="container">
    <h1>Nous contacter</h1>
    <div style="text-align: left;" class="alert alert-success">
        <strong>Vous avez trouvé un bogue ?</strong><br />
        Vous avez trouvé un bogue sur notre site? 
        Envoyez nous l'adresse, notre équipe technique analysera votre demande dans les plus brefs délais.
    </div>
    <form action="/contact" method="post">
        <label for="form_contact">Url : <input type="url" name="url" id="form_contact"></label>
        <button id="btn_contact" type="submit">Envoyer</button>
    </form>
</div>
</body>
</html>